baseURL = "http://b.neni.dev/"
languageCode = "pt-br"
title = "Projeto bilíngue"
description = "Blog com textos e audios em inglês"
theme = "basico"

[params]
repo = "http://github.com/nenitf/blog_projeto-bilingue"
